# Generated by Django 3.2.7 on 2021-10-29 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupForm',
        ),
    ]
