# Generated by Django 3.2.7 on 2021-09-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_image', models.ImageField(upload_to='hotelImg')),
                ('hotel_cuisenes', models.CharField(max_length=200)),
                ('hotel_area', models.CharField(max_length=200)),
                ('hotel_distance', models.DecimalField(decimal_places=1, max_digits=3)),
                ('hotel_time', models.IntegerField()),
                ('hotel_rate', models.DecimalField(decimal_places=1, max_digits=3)),
                ('hotel_offer', models.IntegerField()),
            ],
        ),
    ]
